-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  name character varying,
  email character varying,
  phone character varying,
  address text,
  document_type character varying,
  document_number character varying,
  customer_type character varying DEFAULT 'anonymous'::character varying,
  is_recurrent boolean DEFAULT false,
  anonymous_identifier character varying,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT customers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.devices (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  customer_id uuid,
  brand character varying NOT NULL,
  model character varying NOT NULL,
  device_type character varying NOT NULL,
  serial_number character varying,
  imei character varying,
  color character varying,
  storage_capacity character varying,
  operating_system character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  status USER-DEFINED NOT NULL DEFAULT 'in_store'::device_status,
  created_by uuid,
  CONSTRAINT devices_pkey PRIMARY KEY (id),
  CONSTRAINT fk_devices_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT devices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT devices_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.inventory (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  name character varying NOT NULL,
  description text,
  sku character varying,
  category character varying,
  brand character varying,
  model character varying,
  stock_quantity integer DEFAULT 0,
  min_stock integer DEFAULT 0,
  unit_cost numeric,
  enduser_price numeric,
  recurrent_price numeric,
  supplier character varying,
  location character varying,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT inventory_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.inventory_movements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  inventory_id uuid,
  movement_type character varying NOT NULL,
  quantity integer NOT NULL,
  reason character varying,
  reference_id uuid,
  reference_type character varying,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_movements_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_movements_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT inventory_movements_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT inventory_movements_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.inventory(id)
);
CREATE TABLE public.organization_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  email character varying NOT NULL UNIQUE,
  phone character varying,
  address text,
  subscription_plan character varying DEFAULT 'monthly_6'::character varying,
  owner_name character varying NOT NULL,
  owner_email character varying NOT NULL UNIQUE,
  owner_phone character varying,
  owner_password_hash character varying NOT NULL,
  status character varying DEFAULT 'pending'::character varying,
  approved_by uuid,
  approved_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_requests_pkey PRIMARY KEY (id),
  CONSTRAINT organization_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.organization_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  setting_key character varying NOT NULL,
  setting_value text,
  setting_type character varying DEFAULT 'string'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_settings_pkey PRIMARY KEY (id),
  CONSTRAINT organization_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  email character varying NOT NULL UNIQUE,
  phone character varying,
  address text,
  logo_url text,
  subscription_plan character varying DEFAULT 'monthly_6'::character varying,
  subscription_status character varying DEFAULT 'active'::character varying,
  subscription_start_date timestamp with time zone DEFAULT now(),
  subscription_end_date timestamp with time zone,
  max_users integer DEFAULT 5,
  max_devices integer DEFAULT 100,
  request_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.organization_requests(id)
);
CREATE TABLE public.repair_parts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  repair_id uuid,
  inventory_id uuid,
  quantity integer NOT NULL,
  unit_cost numeric,
  total_cost numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT repair_parts_pkey PRIMARY KEY (id),
  CONSTRAINT repair_parts_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.inventory(id),
  CONSTRAINT repair_parts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT repair_parts_repair_id_fkey FOREIGN KEY (repair_id) REFERENCES public.repairs(id)
);
CREATE TABLE public.repairs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  device_id uuid,
  customer_id uuid,
  created_by uuid,
  title character varying NOT NULL,
  description text,
  problem_description text NOT NULL,
  solution_description text,
  status character varying DEFAULT 'received'::character varying,
  priority character varying DEFAULT 'medium'::character varying,
  estimated_completion_date date,
  actual_completion_date date,
  received_date timestamp with time zone DEFAULT now(),
  delivered_date timestamp with time zone,
  warranty_days integer DEFAULT 30,
  internal_notes text,
  customer_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  unregistered_customer_name character varying,
  unregistered_customer_phone character varying,
  unregistered_device_info text,
  cost numeric,
  CONSTRAINT repairs_pkey PRIMARY KEY (id),
  CONSTRAINT repairs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT repairs_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT repairs_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id),
  CONSTRAINT repairs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.sale_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  sale_id uuid,
  inventory_id uuid,
  quantity integer NOT NULL,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sale_items_pkey PRIMARY KEY (id),
  CONSTRAINT sale_items_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.inventory(id),
  CONSTRAINT sale_items_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id),
  CONSTRAINT sale_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.sales (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  customer_id uuid,
  created_by uuid,
  sale_type character varying DEFAULT 'product'::character varying,
  reference_id uuid,
  subtotal numeric NOT NULL,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  total numeric NOT NULL,
  payment_method character varying,
  payment_status character varying DEFAULT 'paid'::character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_pkey PRIMARY KEY (id),
  CONSTRAINT sales_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT sales_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT sales_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.unlocks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  customer_id uuid,
  device_id uuid,
  created_by uuid,
  unlock_type character varying NOT NULL,
  brand character varying NOT NULL,
  model character varying NOT NULL,
  imei character varying,
  serial_number character varying,
  status character varying DEFAULT 'pending'::character varying,
  cost numeric,
  provider character varying,
  provider_order_id character varying,
  completion_time timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT unlocks_pkey PRIMARY KEY (id),
  CONSTRAINT unlocks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT unlocks_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT unlocks_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id),
  CONSTRAINT unlocks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  email character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  role character varying NOT NULL DEFAULT 'technician'::character varying,
  phone character varying,
  avatar_url text,
  is_active boolean DEFAULT true,
  last_login timestamp with time zone,
  auth_user_id uuid UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);